package com.example.todo_list_backend;

import com.example.todo_list_backend.model.Priority;
import com.example.todo_list_backend.model.ToDo;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

@SpringBootTest
class ToDoListBackendApplicationTests {

    @Test
    void contextLoads() {
    }

    @Test
    void ToDoCreationWithoutDueDateTest(){
        ToDo newToDo = new ToDo("This is a test to-do", Priority.LOW);
        System.out.println(newToDo);
        assert true;
    }

    @Test
    void ToDoCreationAutoIncreasesId(){
        ToDo newToDo = new ToDo("This is a test to-do. It's ID is autogenerated", Priority.LOW);
        ToDo anotherToDo = new ToDo("This is another test to-do. ID should be" +
                "different from the previous one", Priority.MEDIUM);
        System.out.println(newToDo);
        System.out.println(anotherToDo);
        assertNotEquals(newToDo.getId(), anotherToDo.getId());
    }

}
